- name: Install weekly ZFS scrub timer
  template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/system/{{ item }}
    owner: root
    group: root
    mode: 0444
  loop:
    - zfs-scrub.service
    - zfs-scrub.timer
  notify:
    - Reload systemd manager configuration

- name: Enable weekly ZFS scrub timer
  service:
    name: zfs-scrub.timer
    state: started
    enabled: yes

- name: Create ZFS filesystems
  zfs:
    name: "{{ item.name }}"
    state: present
    extra_zfs_properties:
      mountpoint: legacy # used so we can manage with the ansible mount module
  loop: "{{ zfs_mounts }}"

- name: Mount ZFS filesystems
  mount:
    name: "{{ item.mountpoint }}"
    src: "{{ item.name }}"
    fstype: zfs
    state: mounted
  loop: "{{ zfs_mounts }}"
