- name: Install weekly ZFS scrub timer
  template:
    src: "{{ item }}.j2"
    dest: /etc/systemd/system/{{ item }}
    owner: root
    group: root
    mode: 0444
  with_items:
  - zfs-scrub.service
  - zfs-scrub.timer
  notify:
  - Reload systemd manager configuration

- name: Enable weekly ZFS scrub timer
  service: name=zfs-scrub.timer state=started enabled=yes
