---
- name: Get public IPv4 address
  uri: url=https://ipv4.icanhazip.com/ return_content=yes timeout=5
  register: icanhazv4
  ignore_errors: yes

- name: Get public IPv6 address
  uri: url=https://ipv6.icanhazip.com/ return_content=yes timeout=5
  register: icanhazv6
  ignore_errors: yes

- name: Set desertbluffs.com A record
  cloudflare_dns:
    zone: desertbluffs.com
    type: A
    record: desertbluffs.com
    value: "{{ icanhazv4.content | ipv4('address') }}"
    state: present
    account_email: "{{ cloudflare_account_email }}"
    account_api_token: "{{ cloudflare_account_api_token }}"
  when: icanhazv4 | succeeded

- name: Set desertbluffs.com AAAA record
  cloudflare_dns:
    zone: desertbluffs.com
    type: AAAA
    record: desertbluffs.com
    value: "{{ icanhazv6.content | ipv6('address') }}"
    state: present
    account_email: "{{ cloudflare_account_email }}"
    account_api_token: "{{ cloudflare_account_api_token }}"
  when: icanhazv6 | succeeded

- name: Register aliases
  cloudflare_dns:
    zone: desertbluffs.com
    type: CNAME
    value: desertbluffs.com
    record: "{{ item.fqdn }}"
    state: present
    account_email: "{{ cloudflare_account_email }}"
    account_api_token: "{{ cloudflare_account_api_token }}"
  with_items: "{{ proxy_vhosts }}"
