---
- name: Get public IPv4 address
  uri: url=http://ipv4.icanhazip.com return_content=yes timeout=5
  register: icanhazv4
  ignore_errors: yes

- name: Get public IPv6 address
  uri: url=http://ipv6.icanhazip.com return_content=yes timeout=5
  register: icanhazv6
  ignore_errors: yes

- name: Set desertbluffs.com A record via CloudFlare
  cloudflare_dns:
    zone: desertbluffs.com
    type: A
    record: desertbluffs.com
    value: "{{ icanhazv4.content | trim | ipv4('address') }}"
    ttl: 300
    state: present
    account_email: "{{ cloudflare_account_email }}"
    account_api_token: "{{ cloudflare_account_api_token }}"
  when: icanhazv4 | succeeded

- name: Set desertbluffs.com A record via Route 53
  local_action:
    module: route53
    command: create
    zone: desertbluffs.com
    record: desertbluffs.com
    type: A
    value: "{{ icanhazv4.content | trim | ipv4('address') }}"
    ttl: 300
    aws_access_key: "{{ aws_route53_access_key_id }}"
    aws_secret_key: "{{ aws_route53_secret_access_key }}"
    overwrite: yes
  when: icanhazv4 | succeeded

- name: Set desertbluffs.com AAAA record via CloudFlare
  cloudflare_dns:
    zone: desertbluffs.com
    type: AAAA
    record: desertbluffs.com
    value: "{{ icanhazv6.content | trim | ipv6('address') }}"
    ttl: 300
    state: present
    account_email: "{{ cloudflare_account_email }}"
    account_api_token: "{{ cloudflare_account_api_token }}"
  when: icanhazv6 | succeeded

- name: Set desertbluffs.com AAAA record via Route53
  local_action:
    module: route53
    command: create
    zone: desertbluffs.com
    record: desertbluffs.com
    type: A
    value: "{{ icanhazv4.content | trim | ipv4('address') }}"
    ttl: 300
    aws_access_key: "{{ aws_route53_access_key_id }}"
    aws_secret_key: "{{ aws_route53_secret_access_key }}"
    overwrite: yes
  when: icanhazv6 | succeeded

- name: Register aliases via CloudFlare
  cloudflare_dns:
    zone: desertbluffs.com
    type: CNAME
    value: desertbluffs.com
    ttl: 604800
    record: "{{ item.fqdn }}"
    state: present
    account_email: "{{ cloudflare_account_email }}"
    account_api_token: "{{ cloudflare_account_api_token }}"
  with_items: "{{ proxy_vhosts }}"

- name: Register aliases via Route53
  local_action:
    module: route53
    command: create
    zone: desertbluffs.com
    record: "{{ item.fqdn }}"
    type: CNAME
    value: desertbluffs.com
    ttl: 604800
    aws_access_key: "{{ aws_route53_access_key_id }}"
    aws_secret_key: "{{ aws_route53_secret_access_key }}"
    overwrite: yes
  with_items: "{{ proxy_vhosts }}"
