---
- name: Get public IPv4 address
  uri: url=http://ipv4.icanhazip.com return_content=yes timeout=5
  register: icanhazv4
  ignore_errors: yes

- name: Get public IPv6 address
  uri: url=http://ipv6.icanhazip.com return_content=yes timeout=5
  register: icanhazv6
  ignore_errors: yes

- name: Set desertbluffs.com A record via Google Cloud DNS
  local_action:
    module: gcdns_record
    zone: desertbluffs.com
    type: A
    record: desertbluffs.com
    value: "{{ icanhazv4.content | trim | ipv4('address') }}"
    ttl: 3600
    state: present
    credentials_file: "{{ gcp_credentials_file }}"
    project_id: "{{ gcp_project_id }}"
    service_account_email: "{{ gcp_service_account_email }}"
  when: icanhazv4 | succeeded

- name: Set desertbluffs.com A record via Route 53
  local_action:
    module: route53
    command: create
    zone: desertbluffs.com
    record: desertbluffs.com
    type: A
    value: "{{ icanhazv4.content | trim | ipv4('address') }}"
    ttl: 3600
    aws_access_key: "{{ aws_route53_access_key_id }}"
    aws_secret_key: "{{ aws_route53_secret_access_key }}"
    overwrite: yes
  when: icanhazv4 | succeeded

- name: Set desertbluffs.com AAAA record via Google Cloud DNS
  local_action:
    module: gcdns_record
    zone: desertbluffs.com
    type: AAAA
    record: desertbluffs.com
    value: "{{ icanhazv6.content | trim | ipv6('address') }}"
    ttl: 3600
    state: present
    credentials_file: "{{ gcp_credentials_file }}"
    project_id: "{{ gcp_project_id }}"
    service_account_email: "{{ gcp_service_account_email }}"
  when: icanhazv6 | succeeded

- name: Set desertbluffs.com AAAA record via Route53
  local_action:
    module: route53
    command: create
    zone: desertbluffs.com
    record: desertbluffs.com
    type: A
    value: "{{ icanhazv4.content | trim | ipv4('address') }}"
    ttl: 3600
    aws_access_key: "{{ aws_route53_access_key_id }}"
    aws_secret_key: "{{ aws_route53_secret_access_key }}"
    overwrite: yes
  when: icanhazv6 | succeeded

- name: Register aliases via Google Cloud DNS
  local_action:
    module: gcdns_record
    zone: desertbluffs.com
    type: CNAME
    value: desertbluffs.com.
    ttl: 604800
    record: "{{ item.fqdn }}"
    state: present
    credentials_file: "{{ gcp_credentials_file }}"
    project_id: "{{ gcp_project_id }}"
    service_account_email: "{{ gcp_service_account_email }}"
  with_items: "{{ proxy_vhosts }}"

- name: Register aliases via Route53
  local_action:
    module: route53
    command: create
    zone: desertbluffs.com
    record: "{{ item.fqdn }}"
    type: CNAME
    value: desertbluffs.com
    ttl: 604800
    aws_access_key: "{{ aws_route53_access_key_id }}"
    aws_secret_key: "{{ aws_route53_secret_access_key }}"
    overwrite: yes
  with_items: "{{ proxy_vhosts }}"
