---
- include_vars: secret.yml

- name: Install nginx stable pkg
  pkgng: name=nginx state=present

- name: Create nginx log dir
  file: path={{ nginx_log_dir }} state=directory mode=0755 owner={{ nginx_user }} group={{ nginx_group }}

- name: Install nginx static (non-template) config files
  copy:
    src: "{{item}}"
    dest: "{{nginx_conf_root}}/{{item}}"
    owner: root
    group: wheel
    mode: 0444
  with_items:
    - access.lua
    - mime.types

- name: Install main nginx config files
  template:
    src: "{{ item }}.j2"
    dest: "{{ nginx_conf_root }}/{{ item }}"
    owner: www
    group: www
    mode: 0444
  with_items:
    - nginx.conf
    - proxy.conf
    - auth.conf
  notify: reload nginx

- name: Create nginx virtual hosts directory
  file:
    path: "{{ nginx_conf_root }}/vhosts"
    state: directory

- name: Populate virtual hosts configurations
  template: src={{ item }} dest={{ nginx_conf_root }}/vhosts/{{ item | basename | regex_replace('.j2','') }}
  with_fileglob:
    - ../templates/vhosts/*.j2
  notify: reload nginx

- name: Ensure nginx is started and enabled
  service: name=nginx state=started enabled=yes
