---
- name: Download k9s deb package
  ansible.builtin.get_url:
    url: "https://github.com/derailed/k9s/releases/download/{{ k9s_version }}/k9s_Linux_{{ k9s_arch }}.deb"
    dest: "/tmp/k9s.deb"
    mode: '0644'
    checksum: "sha256:{{ k9s_checksum | default(omit) }}"

- name: Install k9s
  ansible.builtin.apt:
    deb: "/tmp/k9s.deb"
    state: present
    force: true

- name: Remove k9s deb package
  ansible.builtin.file:
    path: /tmp/k9s.deb
    state: absent
