---
# SPF records must be double '"quoted"' for Route53
# TXT records must be double '"quoted"' for GCP
# CNAME records must end with a period '.' for GCP: example.org.
dns_records:
- name: desertbluffs.com
  zone: desertbluffs.com
  value:
    - 10 mx.zoho.com.
    - 20 mx2.zoho.com.
  type: MX
  ttl: 86400
- name: desertbluffs.com
  zone: desertbluffs.com
  value: '"v=spf1 mx include:zoho.com ~all"'
  type: SPF
  ttl: 86400
- name: _amazonses.desertbluffs.com
  zone: desertbluffs.com
  value: '"nOSqNz6GuHWUV/GdUWiXEWRTTRMK/ibv6afYRtn5WtU="'
  type: TXT
  ttl: 86400
- name: gc4caluqqezmfk6xanwpdpw5eytglrkn._domainkey.desertbluffs.com
  zone: desertbluffs.com
  value: gc4caluqqezmfk6xanwpdpw5eytglrkn.dkim.amazonses.com.
  type: CNAME
  ttl: 86400
- name: ec25ukpzz6h4nddab3jyevcnzmmmbrgm._domainkey.desertbluffs.com
  zone: desertbluffs.com
  value: ec25ukpzz6h4nddab3jyevcnzmmmbrgm.dkim.amazonses.com.
  type: CNAME
  ttl: 86400
- name: ptusb247sybmwk4i32j5lmagtmtqq7qi._domainkey.desertbluffs.com
  zone: desertbluffs.com
  value: ptusb247sybmwk4i32j5lmagtmtqq7qi.dkim.amazonses.com.
  type: CNAME
  ttl: 86400
- name: desertbluffs.com
  zone: desertbluffs.com
  value: '"keybase-site-verification=QhdmHUpLYp6nSAh5acpWGnHBLYtHRE5JCQGrerXIImI"'
  type: TXT
  ttl: 86400
- name: hypnotoad.desertbluffs.com
  zone: desertbluffs.com
  value: hypnotoad.desertbluffs.com.s3-website-us-east-1.amazonaws.com.
  type: CNAME
  ttl: 604800
