---
- name: Apply common role to all hosts
  hosts: all
  pre_tasks:
    - group_by: key=os_{{ ansible_os_family }}
  roles:
    - common

- name: Configure Kubernetes hosts
  hosts: kubernetes
  roles:
    - eth0
    - zfs
    - iscsi
    - nfs
    - sanoid
    - docker
    - kubernetes

- name: Configure infra hosts
  hosts: infra
  roles:
    - wireguard
    - docker
