---
- name: Apply common role to all hosts
  hosts: all
  pre_tasks:
    - name: Group by operating system
      ansible.builtin.group_by:
        key: "os_{{ ansible_os_family }}"
      changed_when: false
  roles:
    - common
    - networkd

- name: Configure Kubernetes hosts
  hosts: kubernetes
  roles:
    - iscsi
    - nfs
    - containerd
    - kubernetes

- name: Configure infra hosts
  hosts: infra
  roles:
    - pihole
