---
# talk to all hosts just so we can learn about them
- hosts: all
  tasks:
   - group_by: key=os_{{ ansible_distribution }}

- name: configure common settings for FreeBSD hosts
  hosts: os_FreeBSD
  roles:
    - common
    - sshd
    - dhcp6c

- name: configure nginx hosts
  hosts: nginx
  roles:
    - nginx

- hosts: dockerd
  roles:
  - dockerd
