---
- name: Install packages required by Ansible
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Install dmidecode for gather_facts support
      package:
        name: dmidecode
        state: present

- name: Apply common role to all hosts
  hosts: all
  strategy: free
  pre_tasks:
    - group_by: key=os_{{ ansible_os_family }}
  roles:
    - common

- name: Configure docker hosts
  hosts: dockerd
  strategy: free
  roles:
    - eth0
    - zfs
    - sanoid
    - dockerd
