---
# talk to all hosts just so we can learn about them
- hosts: all
  tasks:
   - group_by: key=os_{{ ansible_distribution }}

- name: configure common settings for all hosts
  hosts: all
  roles:
    - common

- name: configure common settings for FreeBSD hosts
  hosts: os_FreeBSD
  roles:
    - sshd

- name: configure nginx hosts
  hosts: nginx
  roles:
    - nginx
    - consul-template

- name: configure plex media server hosts
  hosts: plexmediaserver
  roles:
    - plexmediaserver

- hosts: dockerd
  roles:
  - dockerd
  - zfs
