---
- name: Prepare ODROIDs for Ansible
  hosts: odroid
  gather_facts: no
  roles:
    - odrobian

- name: Apply common role to all hosts
  hosts: all
  pre_tasks:
    - group_by: key=os_{{ ansible_os_family }}
  roles:
    - common

- name: Configure docker hosts
  hosts: dockerd
  roles:
    - eth0
    - zfs
    - dockerd
