---
# gather facts from all hosts
- hosts: all
  tasks:
    - group_by: key=os_{{ ansible_distribution }}

- name: configure common settings for all hosts
  hosts: all
  roles:
    - common

- name: configure common settings for FreeBSD hosts
  hosts: os_FreeBSD
  roles:
    - sshd

- name: configure nginx hosts
  hosts: nginx
  roles:
    - consul-template
    - nginx

- name: configure plex media server hosts
  hosts: plexmediaserver
  roles:
    - plexmediaserver

- name: configure docker hosts
  hosts: dockerd
  roles:
    - dockerd
    - zfs

- name: configure dnsmasq hosts
  hosts: dnsmasq
  roles:
    - dnsmasq

# - name: launch droplets on Digital Ocean
#   hosts: localhost
#   roles:
#     - droplet
