---
- name: Apply common role to all but FreeNAS hosts
  hosts: all:!freenas
  pre_tasks:
    - group_by: key=os_{{ ansible_os_family }}
  roles:
    - common

- name: Configure Kubernetes hosts
  hosts: kubernetes
  roles:
    - eth0
    - zfs
    - iscsi
    - nfs
    - sanoid
    - docker
    - kubernetes

- name: Configure infra hosts
  hosts: infra
  roles:
    - wireguard
    - docker
    - pihole-docker

- name: Configure FreeNAS hosts
  hosts: freenas
  gather_facts: no
  become: no
  roles:
    - freenas
