---
- name: Apply common role to all hosts
  hosts: all
  pre_tasks:
    - group_by: key=os_{{ ansible_os_family }}
  roles:
    - common

- name: Configure dockerd hosts
  hosts: dockerd
  roles:
    - eth0
    - zfs
    - sanoid
    - dockerd

- name: Configure infra hosts
  hosts: infra
  roles:
    - wireguard
