---
# gather facts from all hosts
- hosts: all
  tasks:
    - group_by: key=os_{{ ansible_distribution }}

- name: configure common settings for all hosts
  hosts: remotehosts
  roles:
    - common

- name: configure common settings for FreeBSD hosts
  hosts: os_FreeBSD
  roles:
    - sshd

- name: configure nginx hosts
  hosts: nginx
  roles:
    - nginx
    - consul-template

- name: configure plex media server hosts
  hosts: plexmediaserver
  roles:
    - plexmediaserver
    - consul

- name: configure docker hosts
  hosts: dockerd
  roles:
    - dockerd
    - zfs

- name: configure dnsmasq hosts
  hosts: dnsmasq
  roles:
    - dnsmasq

- name: perform tasks on localhost
  hosts: localhost
  roles:
    - droplet
