---
# gather facts from all hosts
- hosts: all
  tasks:
    - group_by: key=os_{{ ansible_os_family }}

- name: configure common settings for all hosts
  hosts: all
  roles:
    - common

- name: configure docker hosts
  hosts: dockerd
  roles:
    - eth0
    - zfs
    - dockerd
