---
- name: Apply common role to all but FreeNAS hosts
  hosts: all:!freenas:!jails
  pre_tasks:
    - group_by: key=os_{{ ansible_os_family }}
  roles:
    - common

- name: Configure zfs
  hosts: zfs
  roles:
    - zfs
    - sanoid

- name: Configure Kubernetes hosts
  hosts: kubernetes
  roles:
    - iscsi
    - nfs
    - docker
    - crio
    - kubernetes

- name: Configure infra hosts
  hosts: infra
  roles:
    - wireguard
    - healthchecks_io

- name: Configure pihole hosts
  hosts: pihole
  roles:
    - crio
    - pihole-docker

- name: Configure FreeNAS hosts
  hosts: freenas
  gather_facts: no
  become: no
  roles:
    - freenas

- name: Configure nzbget
  hosts: nzbget
  roles:
    - nzbget
