---
- name: Apply common role to all but TrueNAS hosts
  hosts: all:!truenas
  pre_tasks:
    - name: Group by operating system
      ansible.builtin.group_by:
        key: "os_{{ ansible_os_family }}"
  roles:
    - common

- name: Configure Kubernetes hosts
  hosts: kubernetes
  roles:
    - iscsi
    - nfs
    - crio
    - kubernetes

- name: Configure infra hosts
  hosts: infra
  roles:
    - healthchecks_io
    - pihole

- name: Configure TrueNAS hosts
  hosts: truenas
  gather_facts: false
  become: false
  roles:
    - truenas
