---
# apply bootstrap role to odrobian odroids so we can use ansible with them
- hosts: odroid
  gather_facts: no
  roles:
    - odrobian

# gather facts from all hosts
- hosts: all
  pre_tasks:
    - group_by: key=os_{{ ansible_os_family }}
  roles:
    - common

- name: configure docker hosts
  hosts: dockerd
  roles:
    - eth0
    - zfs
    - dockerd
