---
- name: Apply common role to all but TrueNAS hosts
  hosts: all:!truenas:!jails
  pre_tasks:
    - group_by: key=os_{{ ansible_os_family }}
  roles:
    - common

- name: Configure zfs
  hosts: zfs
  roles:
    - zfs
    - sanoid

- name: Configure Kubernetes hosts
  hosts: kubernetes
  roles:
    - iscsi
    - nfs
    - crio
    - kubernetes

- name: Configure infra hosts
  hosts: infra
  roles:
    - healthchecks_io
    - pihole

- name: Configure TrueNAS hosts
  hosts: truenas
  gather_facts: false
  become: false
  roles:
    - truenas

- name: Configure nzbget
  hosts: nzbget
  roles:
    - nzbget
