---
docker_daemon_port: 2376
docker_sysctls:
  net.ipv4.ip_forward: 1
  net.bridge.bridge-nf-call-ip6tables: 1
  net.bridge.bridge-nf-call-iptables: 1
  net.netfilter.nf_conntrack_max: 1000000
  net.core.somaxconn: 1024
  vm.panic_on_oom: 1
  kernel.panic: 10
  net.ipv4.tcp_syncookies: 0
docker_package_name: docker-ce
# This value will be used for apt version pinning and should follow
# the latest Docker version validated
docker_package_version: 18.06*
docker_storage_driver: overlay2
docker_live_restore: false
