- name: Create per-minute WAN connection heartbeat cron
  cron:
    name: Per-minute WAN conection heartbeat
    minute: '*'
    hour: '*'
    day: '*'
    weekday: '*'
    month: '*'
    user: nobody
    job: "curl -fsS --retry 3 {{ hc_url }} > /dev/null"
    cron_file: wan_connection_heartbeat
  when: hc_url is defined
