---
- name: Add cri-o package signing key
  ansible.builtin.apt_key:
    url: https://download.opensuse.org/repositories/isv:/cri-o:/stable:/{{ crio_kubernetes_version }}/deb/Release.key
    keyring: /etc/apt/keyrings/cri-o-apt-keyring.gpg
    state: present

- name: Add cri-o apt repo
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://download.opensuse.org/repositories/isv:/cri-o:/stable:/{{ crio_kubernetes_version }}/deb/ /
    filename: cri-o

- name: Install CRI-O packages
  package:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - cri-o
      - conmon

- name: Configure CRI-O
  template:
    src: crio.conf.j2
    dest: /etc/crio/crio.conf
    owner: root
    group: root
    mode: '0644'

- name: Create cni net.d dir
  file:
    dest: /etc/cni/net.d/
    state: directory
    mode: '0755'
    owner: root
    group: root

# - name: Configure CRI-O bridge
#   template:
#     src: crio-bridge.conf.j2
#     dest: /etc/cni/net.d/100-crio-bridge.conf
#     owner: root
#     group: root
#     mode: '0644'

- name: Start and enable CRI-O
  service:
    name: crio
    enabled: true
    state: started
    daemon_reload: true
