---
- name: Add Kubic package signing key
  apt_key:
    url: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable/x{{ ansible_distribution }}_{{ ansible_distribution_version }}/Release.key

- name: Add Kubic apt repo
  apt_repository:
    repo: deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/x{{ ansible_distribution }}_{{ ansible_distribution_version }} /
    filename: kubic

- name: Install CRI-O packages
  package:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - cri-o-1.17
      - cri-o-runc

- name: Configure CRI-O
  template:
    src: crio.conf.j2
    dest: /etc/crio/crio.conf
    owner: root
    group: root
    mode: '0644'

- name: Create cni net.d dir
  file:
    dest: /etc/cni/net.d/
    state: directory
    mode: '0755'
    owner: root
    group: root

- name: Configure CRI-O bridge
  template:
    src: crio-bridge.conf.j2
    dest: /etc/cni/net.d/100-crio-bridge.conf
    owner: root
    group: root
    mode: '0644'

- name: Start and enable CRI-O
  service:
    name: crio
    enabled: true
    state: started
    daemon_reload: true
