- name: Add Docker’s official GPG key
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    id: 0EBFCD88
    state: present

- name: Install Kubernetes apt repo
  apt_repository:
    repo: 'deb https://download.docker.com/linux/ubuntu {{ansible_distribution_release|lower}} stable'
    filename: docker
    state: present
    update_cache: yes

- name: Pin Docker version
  copy:
    dest: /etc/apt/preferences.d/docker-ce
    content: |
      Package: docker-ce
      Pin: version 17.03*
      Pin-Priority: 1001

- name: Install Docker package
  package:
    name: docker-ce
    state: latest

- name: Configure Docker
  template:
    src: docker.service
    dest: /etc/systemd/system/docker.service
  notify:
    - Restart Docker

- name: Enable and start Docker daemon
  service:
    name: docker
    enabled: yes
    state: started
