- name: Install Google Cloud Packages Automatic Signing Key
  apt_key:
    url: 'https://packages.cloud.google.com/apt/doc/apt-key.gpg'
    id: 3746C208A7317B0F
    state: present

- name: Install Kubernetes apt repo
  apt_repository:
    repo: 'deb http://apt.kubernetes.io/ kubernetes-{{ansible_distribution_release|lower}} main'
    filename: kubernetes
    state: present
    update_cache: yes

- name: Install Kubernetes packages
  package:
    name: "{{item}}"
    state: present
  with_items:
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni

- name: Start and enable Kubelet
  service:
    name: kubelet
    enabled: yes
    state: started

