---
- include: tasks/smb.yml # SMB mounts setup
  when: smb_mounts is defined
- include: tasks/nfs.yml # NFS mounts setup
  when: nfs_mounts is defined
- include: tasks/zfs.yml # ZFS mounts setup
  when: zfs_mounts is defined

- include: net.yml
- include: dockerfs.yml

- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Configure Docker
  template:
    src: docker.service
    dest: /etc/systemd/system/docker.service
  notify:
    - Reload systemd manager configuration
    - Restart Docker

- name: Enable and start Docker daemon
  service: name=docker enabled=yes state=started

- include: kubernetes.yml
