---
- include: tasks/smb.yml # SMB mounts setup
  when: smb_mounts is defined
- include: tasks/nfs.yml # NFS mounts setup
  when: nfs_mounts is defined
- include: tasks/zfs.yml # ZFS mounts setup
  when: zfs_mounts is defined

- include: net.yml

- name: Create dockerfs group
  group: name=dockerfs

- name: Create dockerfs user
  user: name=dockerfs shell=/bin/false createhome=no home=/nonexistent group=dockerfs groups=

- name: Install Docker
  package: name="{{ item }}" state=present
  with_items:
    - docker
    - net-tools

- name: Create dockerfs dirs
  file: 
    name: "/dockerfs/{{ item.name }}"
    state: directory
    owner: "{{ item.owner | default('dockerfs') }}"
    group: "{{ item.group | default('dockerfs') }}"
    recurse: true
  with_items: "{{ dockerfs_dirs }}"

- name: Enable and start Docker daemon
  service: name=docker enabled=yes state=running
