---
- include_tasks: tasks/smb.yml # SMB mounts setup
  when: smb_mounts is defined
- include_tasks: tasks/nfs.yml # NFS mounts setup
- include_tasks: tasks/zfs.yml # ZFS mounts setup
  when: zfs_mounts is defined

- import_tasks: net.yml
- import_tasks: dockerfs.yml
- import_tasks: docker.yml
- import_tasks: kubernetes.yml
