---
- include_tasks: tasks/smb.yml # SMB mounts setup
  when: smb_mounts is defined
- include_tasks: tasks/nfs.yml # NFS mounts setup
  when: nfs_mounts is defined
- include_tasks: tasks/zfs.yml # ZFS mounts setup
  when: zfs_mounts is defined

- import_tasks: net.yml
- import_tasks: dockerfs.yml


# - name: Configure Docker
#   template:
#     src: docker.service
#     dest: /etc/systemd/system/docker.service
#   notify:
#     - Reload systemd manager configuration
#     - Restart Docker

- import_tasks: docker.yml
- import_tasks: kubernetes.yml
