---
- include: tasks/ovs.yml # Open vSwitch setup
  when: do_ovs == True
- include: tasks/smb.yml # SMB mounts setup
  when: do_smb == True

- name: Install Docker
  package: name=docker state=present

- file: path=/etc/systemd/system/docker.service.d state=directory mode=0755

- name: Configure Docker listening port
  template:
    src: docker.conf.j2
    dest: /etc/systemd/system/docker.service.d/docker.conf
    owner: root
    group: root
    mode: 0644
  notify:
  - Reload systemd manager configuration
  - Restart Docker

- name: Enable and start Docker daemon
  service: name=docker enabled=yes state=running

- group: name=dockerfs
- user: name=dockerfs shell=/bin/false createhome=no home=/nonexistent group=dockerfs groups=

- file: name={{ item }} state=directory owner=dockerfs group=dockerfs recurse=true
  with_items:
  - /dockerfs/nzbget/config
  - /dockerfs/deluge/config
  - /dockerfs/couchpotato/config
  - /dockerfs/sonarr/config
  - /dockerfs/plexpy/config
