# http://ebtables.netfilter.org/documentation/bridge-nf.html
- name: Load bridge-netfilter
  modprobe:
    name: br_netfilter
    state: present

# https://wiki.archlinux.org/index.php/kernel_modules#Using_files_in_.2Fetc.2Fmodprobe.d.2F
- name: Load bridge-netfilter at startup
  copy:
    content: br_netfilter
    dest: /etc/modules-load.d/br_netfilter.conf

- name: Set Docker sysctls
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: yes
    reload: yes
    sysctl_file: /etc/sysctl.d/60-docker.conf
  loop: "{{ lookup('dict', docker_sysctls) }}"

# https://www.freedesktop.org/software/systemd/man/systemd-sysctl.service.html
- name: Start and enable the systemd-sysctl service
  service:
    name: systemd-sysctl
    state: started
    enabled: yes
