---
- include_vars:
    dir: vars
    files_matching: '{{ansible_os_family}}.yml'

- name: Install NFS utils
  package:
    name: '{{nfs_utils}}'
    state: present

- name: Mount NFS shares
  mount:
    name: "{{ item.dest }}"
    src: "{{ item.src }}"
    fstype: nfs4
    state: mounted
  with_items: "{{ nfs_mounts }}"

- name: Start and enable rpcbind
  service:
    name: rpcbind
    enabled: yes
    state: started

