---
- name: Install NFS utils
  package: name=nfs-utils state=present

- name: Mount NFS shares 
  mount:
    name: "{{ item.dest }}"
    src: "{{ item.src }}"
    fstype: nfs4
    state: mounted
  with_items: "{{ nfs_mounts }}"
