---
- name: Install NFS utils
  package: name=nfs-utils state=present

- name: Install autofs
  package: name=autofs state=present

- name: Start and enable autofs
  service: name=autofs state=started enabled=yes
