---
- name: Install CIFS utils
  package: name=cifs-utils state=present

- name: Mount SMB shares share
  mount:
    name: "{{ item.dest }}"
    src: "{{ item.src }}"
    fstype: cifs
    state: mounted
    opts: "noperm,vers=3.0,username=guest,password=guest{{ item.opts | default('') }}"
  with_items: "{{ smb_mounts }}"

- name: Wait for network on boot
  service: name=systemd-networkd-wait-online enabled=yes
