- name: Create ZFS filesystems
  zfs:
    name: "{{ item.name }}"
    state: present
    extra_zfs_properties:
      mountpoint: legacy # used so we can manage with the ansible mount module
  loop: "{{ zfs_mounts }}"

- name: Mount ZFS filesystems
  mount:
    name: "{{ item.mountpoint }}"
    src: "{{ item.name }}"
    fstype: zfs
    state: mounted
  loop: "{{ zfs_mounts }}"
