#!/bin/sh

# PROVIDE: consul-template
# REQUIRE: DAEMON
# BEFORE: NETWORKING
# KEYWORD: shutdown

# Add the following lines to
# /etc/rc.conf.d/consul-template /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# consul_template_enable (bool):			Set to NO by default.
#		Set it to YES to enable consul-template.
# consul_template_config (path):			Set to /usr/local/etc/consul-template.conf
#		by default.
# consul_template_pidfile (path):		Set to /var/run/consul-template.pid
#		by default.
# consul_template_flags (additional arguments):	Not defined by default.
#

. /etc/rc.subr

name="consul_template"
rcvar="consul_template_enable"
start_cmd="${name}_start"

command="/usr/local/bin/consul-template"

load_rc_config $name

: ${consul_template_enable="NO"}
: ${consul_template_config="/usr/local/etc/consul-template.conf"}
: ${consul_template_pidfile="/var/run/consul-template.pid"}

pidfile="${consul_template_pidfile}"
command_args="-config=${consul_template_config} -pid-file=${consul_template_pidfile} ${consul_template_flags}"

consul_template_start(){
  echo "Starting ${name}."
  ${command} ${command_args} >/var/log/${name}.log 2>&1 &
}

run_rc_command "$1"
