---
- name: Install NFS utils
  package:
    name: '{{ nfs_utils }}'
    state: present

- name: Ensure mount points exist
  file:
    path: "{{ item.dest }}"
    state: directory
  loop: "{{ nfs_mounts }}"
  when: nfs_mounts is defined

- name: Mount NFS shares
  mount:
    path: "{{ item.dest }}"
    src: "{{ item.src }}"
    fstype: nfs4
    state: mounted
  loop: "{{ nfs_mounts }}"
  when: nfs_mounts is defined

- name: Start and enable rpcbind
  service:
    name: rpcbind
    enabled: yes
    state: started
