---
- name: Install NFS utils
  package:
    name: '{{ nfs_utils }}'
    state: present

- name: Ensure mount points exist
  ansible.builtin.file:
    path: "{{ item.dest }}"
    state: directory
    mode: 0755
  loop: "{{ nfs_mounts }}"
  when: nfs_mounts is defined

- name: Mount NFS shares
  ansible.posix.mount:
    path: "{{ item.dest }}"
    src: "{{ item.src }}"
    opts: "{{ item.opts | default(omit) }}"
    fstype: nfs4
    state: mounted
  loop: "{{ nfs_mounts }}"
  when: nfs_mounts is defined

- name: Start and enable rpcbind
  ansible.builtin.service:
    name: rpcbind
    enabled: true
    state: started
