---
- name: Ensure the DHCPv6 client is installed
  pkgng: name=dhcp6 state=present

- name: Configure the DHCPv6 client
  template: src=dhcp6c.conf.j2 dest=/usr/local/etc/dhcp6c.conf
  notify: restart dhcp6c

- name: Removing existing DHCPv6 interfaces lines
  lineinfile:
    dest: /etc/rc.conf.local
    regexp: "^dhcp6c_interfaces="
    state: absent

- name: Enable the DHCPv6 client on particular interfaces
  lineinfile:
    dest=/etc/rc.conf.local
    line="dhcp6c_interfaces=\"{{ ansible_default_ipv4.device }}\""
    owner=root
    group=wheel
    mode=0644
    create=yes
  notify: restart dhcp6c

- name: Ensure the DHCPv6 client is running and enabled
  service: name=dhcp6c state=started enabled=yes
