---
- name: Install keepalived
  ansible.builtin.package:
    name: keepalived
    state: present

- name: Configure keepalived
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart keepalived

- name: Enable and start keepalived
  ansible.builtin.service:
    name: keepalived
    enabled: true
    state: started
