- name: Install Docker apt repo
  apt_repository:
    repo: 'deb https://download.docker.com/linux/ubuntu {{ansible_distribution_release|lower}} stable'
    filename: docker
    state: present
    update_cache: yes

- name: Install Google Cloud Packages Automatic Signing Key
  apt_key:
    url: 'https://packages.cloud.google.com/apt/doc/apt-key.gpg'
    id: BA07F4FB
    state: present

- name: Install Kubernetes apt repo
  apt_repository:
    repo: 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
    filename: kubernetes
    state: present
    update_cache: yes

- name: Pin versions on Kubernetes packages
  template:
    src: kubernetes_apt_pins
    dest: /etc/apt/preferences.d/kubernetes

- name: Install Kubernetes packages
  package:
    name: "{{ kubernetes_packages }}"
    force: yes

- name: Install supporting Kubernetes packages
  package:
    name: "{{ kubernetes_other_packages }}"

- name: Configure kubelet
  template:
    src: etc_default_kubelet
    dest: /etc/default/kubelet
    mode: 0640

- name: Start and enable Kubelet
  service:
    name: kubelet
    enabled: yes
    state: started

- name: Configure keepalived vrrp for stacked Kubernetes masters
  include_tasks: keepalived.yaml
