---
- name: Set Kubernetes sysctls
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: yes
    reload: yes
    sysctl_file: /etc/sysctl.d/70-k8s.conf
    ignoreerrors: yes # ignores unknown key errors
  loop: "{{ lookup('dict', kubernetes_sysctls, wantlist=true) }}"

- name: Install Google Cloud Packages Automatic Signing Key
  apt_key:
    url: 'https://packages.cloud.google.com/apt/doc/apt-key.gpg'
    id: BA07F4FB
    state: present

- name: Install Kubernetes apt repo
  apt_repository:
    repo: 'deb http://apt.kubernetes.io/ kubernetes-xenial main'
    filename: kubernetes
    state: present
    update_cache: true

- name: Pin versions on Kubernetes packages
  template:
    src: kubernetes_apt_pins
    dest: /etc/apt/preferences.d/kubernetes

- name: Install Kubernetes packages
  package:
    name: "{{ kubernetes_packages }}"
    force: true

- name: Install supporting Kubernetes packages
  package:
    name: "{{ kubernetes_other_packages }}"

- name: Configure kubelet for CRI-O
  template:
    src: etc_default_kubelet
    dest: /etc/default/kubelet
    mode: 0640

- name: Start and enable Kubelet
  service:
    name: kubelet
    enabled: true
    state: started

- name: Configure keepalived vrrp for stacked Kubernetes masters
  include_tasks: keepalived.yaml
