---
- name: Install consul-template package
  package: name=consul-template state=present

- name: Install consul-template init script
  copy: src=consul-template dest=/usr/local/etc/rc.d/consul-template owner=root group=wheel mode=0555

- name: Install consul-template configuration
  template: src=consul-template.conf.j2 dest=/usr/local/etc/consul-template.conf owner=root group=wheel mode=0444
  notify: restart consul-template

- name: Start and enable consul-template service
  service: name=consul-template state=started enabled=yes
