- user:
    name: nzbget
    shell: /sbin/nologin
    home: /var/empty
    create_home: no
    uid: 1001

- name: Try to get nzbget version
  command: /opt/nzbget/nzbget --version
  register: nzbget_version
  ignore_errors: true
  changed_when: false

- name: Ensure version is expected
  assert:
    that:
      - nzbget_version is succeeded
      - "'nzbget version: ' ~ nzbget_expected_version in nzbget_version.stdout"
  ignore_errors: true
  register: version_ok

- block:
    - name: Fetch nzbget installer
      get_url:
        url: "{{ nzbget_package.url }}"
        checksum: "{{ nzbget_package.checksum }}"
        dest: /root/nzbget-{{ nzbget_expected_version }}-bin-freebsd.run

    - name: Run nzbget installer
      command: /bin/sh /root/nzbget-{{ nzbget_expected_version }}-bin-freebsd.run --destdir /opt/nzbget
      notify: restart nzbget
  when: version_ok is failed

- name: Write nzbget init script
  template:
    src: rc.d_nzbget.j2
    dest: /etc/rc.d/nzbget
    owner: root
    group: wheel
    mode: 0755
  notify: restart nzbget

- name: Install archive tools
  package:
    name: "{{ packages }}"
  vars:
    packages:
      - unrar
      - p7zip

- name: Write nzbget config
  template:
    src: nzbget.conf.j2
    dest: /etc/nzbget.conf
    owner: nzbget
    group: nzbget
    mode: 0600
    backup: yes
  notify: restart nzbget

- name: Ensure nzbget owns its working dirs
  file:
    dest: /opt/nzbget
    recurse: true
    owner: nzbget
    group: nzbget

- name: Start and enable nzbget
  service:
    name: nzbget
    state: started
    enabled: yes
