- user:
    name: nzbget
    shell: /sbin/nologin
    home: /var/empty
    create_home: no
    uid: 1000

- name: Try to get nzbget version
  command: /opt/nzbget/nzbget --version
  register: nzbget_version
  ignore_errors: true
  changed_when: false

- name: Ensure version is expected
  assert:
    that:
      - nzbget_version is succeeded
      - "'nzbget version: 20.0' in nzbget_version.stdout"
  ignore_errors: true
  register: version_ok

- block:
    - name: Fetch nzbget installer
      get_url:
        url: https://github.com/nzbget/nzbget/releases/download/v20.0/nzbget-20.0-bin-freebsd.run
        checksum: sha256:609dbcedb71498bb79697c2cb18da88d7e5183eebed1fde3abf4a0e32bb6e7d7
        dest: /root/nzbget-20.0-bin-freebsd.run

    - name: Run nzbget installer
      command: /bin/sh /root/nzbget-20.0-bin-freebsd.run --destdir /opt/nzbget
  when: version_ok is failed

- name: Write nzbget init script
  template:
    src: rc.d_nzbget.j2
    dest: /etc/rc.d/nzbget
    owner: root
    group: wheel
    mode: 0755

- name: Write nzbget config
  template:
    src: nzbget.conf.j2
    dest: /etc/nzbget.conf
    owner: nzbget
    group: nzbget
    mode: 0600
    backup: yes

- name: Ensure nzbget owns its working dirs
  file:
    dest: /opt/nzbget
    recurse: true
    owner: nzbget
    group: nzbget

- name: Start and enable nzbget
  service:
    name: nzbget
    state: started
    enabled: yes
