---
- apt:
    deb: https://secure.nic.cz/files/knot-resolver/knot-resolver-release.deb

- apt:
    package: knot-resolver
    update_cache: true

- template:
    src: kresd.conf.j2
    dest: /etc/knot-resolver/kresd.conf
  notify: restart knot

- file:
    path: /etc/systemd/system/kresd.socket.d
    state: directory
    recurse: true

- template:
    src: kresd-socket-override.conf.j2
    dest: /etc/systemd/system/kresd.socket.d/override.conf
  notify:
    - restart knot

- file:
    path: /etc/knot-resolver/rpz.zone
    state: touch

- service:
    name: kresd@1
    enabled: true
    state: started
