---
docker_daemon_port: 2376
do_ovs: False
do_smb: True
smb_mounts:
  - { src: "//freenas.radoncanyon.com/media", dest: "/mnt/media" }
  - { src: "//freenas.radoncanyon.com/plex_logs", dest: "/mnt/plex_logs" }
  - { src: "//freenas.radoncanyon.com/syncthing", dest: "/mnt/syncthing", opts: ",file_mode=0750,dir_mode=0750,uid=1001,gid=1001" }
dockerfs_dirs:
  - { name: "/dockerfs/nzbget/config" }
  - { name: "/dockerfs/deluge/config" }
  - { name: "/dockerfs/couchpotato/config" }
  - { name: "/dockerfs/sonarr/config" }
  - { name: "/dockerfs/plexpy/config" }
  - { name: "/dockerfs/nzbget/config" }
  - { name: "/dockerfs/syncthing/config" }
  - { name: "/dockerfs/pritunl/pritunl" }
  - { name: "/dockerfs/pritunl/mongodb" }
  - { name: "/dockerfs/unifi/config" }
  - { name: "/dockerfs/grafana/data" }
  - { name: "/dockerfs/influxdb/data" }
  - { name: "/dockerfs/prometheus/data" }
  - { name: "/dockerfs/jenkins/data", owner: 1000, group: 1000 }
  - { name: "/dockerfs/oauth2_proxy/config" }
  - { name: "/dockerfs/consul/data", owner: 100, group: 1000 }
  - { name: "/dockerfs/consul/config", owner: 100, group: 1000 }
