---
docker_daemon_port: 2376
do_ovs: False
do_smb: True
smb_mounts:
  - { src: "//freenas.radoncanyon.com/media", dest: "/mnt/media", opts: }
  - { src: "//freenas.radoncanyon.com/plex_logs", dest: "/mnt/plex_logs", opts: }
  - { src: "//freenas.radoncanyon.com/syncthing", dest: "/mnt/syncthing", opts: ",file_mode=0750,dir_mode=0750,uid=1001,gid=1001" }
dockerfs_dirs:
  - { name: "/dockerfs/nzbget/config", owner: "dockerfs", group: "dockerfs" }
  - { name: "/dockerfs/deluge/config", owner: "dockerfs", group: "dockerfs" }
  - { name: "/dockerfs/couchpotato/config", owner: "dockerfs", group: "dockerfs" }
  - { name: "/dockerfs/sonarr/config", owner: "dockerfs", group: "dockerfs" }
  - { name: "/dockerfs/plexpy/config", owner: "dockerfs", group: "dockerfs" }
  - { name: "/dockerfs/nzbget/config", owner: "dockerfs", group: "dockerfs" }
  - { name: "/dockerfs/syncthing/config", owner: "dockerfs", group: "dockerfs" }
  - { name: "/dockerfs/pritunl/pritunl", owner: "dockerfs", group: "dockerfs" }
  - { name: "/dockerfs/pritunl/mongodb", owner: "dockerfs", group: "dockerfs" }
  - { name: "/dockerfs/unifi/config", owner: "dockerfs", group: "dockerfs" }
  - { name: "/dockerfs/dnsmasq/config", owner: "dockerfs", group: "dockerfs" }
