---
docker_daemon_port: 2376
do_ovs: False
do_smb: True
smb_mounts:
  - { src: "//freenas.radoncanyon.com/media", dest: "/mnt/media" }
  - { src: "//freenas.radoncanyon.com/plex_logs", dest: "/mnt/plex_logs" }
  - { src: "//freenas.radoncanyon.com/owncloud", dest: "/mnt/owncloud" }
