---
docker_daemon_port: 2376
do_ovs: False
nfs_mounts:
  - { src: "freenas.radoncanyon.com:/mnt/etank/media/tv", dest: "/mnt/media/tv" }
  - { src: "freenas.radoncanyon.com:/mnt/etank/media/movies", dest: "/mnt/media/movies" }
  - { src: "freenas.radoncanyon.com:/mnt/etank/media/anime", dest: "/mnt/media/anime" }
  - { src: "freenas.radoncanyon.com:/mnt/etank/media/downloads", dest: "/mnt/downloads" }
smb_mounts:
  - { src: "//freenas.radoncanyon.com/plex_logs", dest: "/mnt/plex_logs" }
dockerfs_dirs:
  - { name: "/dockerfs/consul/config", owner: 100, group: 1000 }
  - { name: "/dockerfs/consul/data", owner: 100, group: 1000 }
  - { name: "/dockerfs/couchpotato/config" }
  - { name: "/dockerfs/deluge/config" }
  - { name: "/dockerfs/gitea-mysql/data", owner: 999, group: 999 }
  - { name: "/dockerfs/gitea/data", owner: 1000, group: 1000 }
  - { name: "/dockerfs/jenkins/data", owner: 1000, group: 1000 }
  - { name: "/dockerfs/nzbget/config" }
  - { name: "/dockerfs/nzbget/config" }
  - { name: "/dockerfs/oauth2_proxy/config" }
  - { name: "/dockerfs/plexpy/config" }
  - { name: "/dockerfs/pritunl/mongodb" }
  - { name: "/dockerfs/pritunl/pritunl" }
  - { name: "/dockerfs/sonarr/config" }
  - { name: "/dockerfs/unifi/config" }
