---
docker_daemon_port: 2376
nfs_mounts:
- { src: "freenas.radoncanyon.com:/mnt/etank/media/tv", dest: "/mnt/media/tv" }
- { src: "freenas.radoncanyon.com:/mnt/etank/media/movies", dest: "/mnt/media/movies" }
- { src: "freenas.radoncanyon.com:/mnt/etank/media/anime", dest: "/mnt/media/anime" }
- { src: "freenas.radoncanyon.com:/mnt/etank/media/downloads", dest: "/mnt/media/downloads" }
dockerfs_dirs:
- { name: "couchpotato/config" }
- { name: "nzbget/config" }
- { name: "nzbget/intermediate" }
- { name: "plexpy/config" }
- { name: "pms/config" }
- { name: "pms/transcode" }
- { name: "sonarr/config" }
- { name: "radarr/config" }
- { name: "smokeping/data" }
- { name: "smokeping/config" }
- { name: "unifi/config" }
- { name: "deluge/config" }
zfs_mounts:
- { name: rpool/dockerfs, mountpoint: /dockerfs }
nfs_utils: nfs-utils
