---
docker_daemon_port: 2376
nfs_mounts:
dockerfs_dirs:
  - { name: "pms/transcode" }
  - { name: "nzbget/intermediate" }
zfs_mounts:
  - { name: rpool/dockerfs, mountpoint: /dockerfs }
nfs_utils: nfs-utils
