---
docker_daemon_port: 2376
do_ovs: False
do_smb: True
smb_mounts:
  - { src: "//freenas.radoncanyon.com/media", dest: "/mnt/media", opts: }
  - { src: "//freenas.radoncanyon.com/plex_logs", dest: "/mnt/plex_logs", opts: }
  - { src: "//freenas.radoncanyon.com/owncloud", dest: "/mnt/owncloud", opts: ",file_mode=0750,dir_mode=0750,uid=33,gid=33" }
dockerfs_dirs:
  - { name: "/dockerfs/nzbget/config", owner: "dockerfs", group: "dockerfs" }
  - { name: "/dockerfs/deluge/config", owner: "dockerfs", group: "dockerfs" }
  - { name: "/dockerfs/couchpotato/config", owner: "dockerfs", group: "dockerfs" }
  - { name: "/dockerfs/sonarr/config", owner: "dockerfs", group: "dockerfs" }
  - { name: "/dockerfs/plexpy/config", owner: "dockerfs", group: "dockerfs" }
  - { name: "/dockerfs/nzbget/config", owner: "dockerfs", group: "dockerfs" }
  - { name: "/dockerfs/owncloud/config", owner: 33, group: 33 }
  - { name: "/dockerfs/owncloud/apps", owner: 33, group: 33 }
  - { name: "/dockerfs/owncloud_db/data", owner: 999, group: 999 }
  - { name: "/dockerfs/owncloud_db/config", owner: 999, group: 999 }
  - { name: "/dockerfs/crashplan/data", owner: "dockerfs", group: "dockerfs" }
  - { name: "/dockerfs/crashplan/config", owner: "dockerfs", group: "dockerfs" }
