---
docker_daemon_port: 2376
nfs_mounts:
- { src: "nas1.radoncanyon.com:/mnt/etank/media/tv", dest: "/mnt/media/tv/nas1" }
- { src: "nas2.radoncanyon.com:/mnt/etank/media/tv", dest: "/mnt/media/tv/nas2" }
- { src: "nas1.radoncanyon.com:/mnt/etank/media/movies", dest: "/mnt/media/movies/nas1" }
- { src: "nas2.radoncanyon.com:/mnt/etank/media/movies", dest: "/mnt/media/movies/nas2" }
- { src: "nas1.radoncanyon.com:/mnt/etank/media/anime", dest: "/mnt/media/anime/nas1" }
- { src: "nas2.radoncanyon.com:/mnt/etank/media/anime", dest: "/mnt/media/anime/nas2" }
- { src: "nas1.radoncanyon.com:/mnt/etank/media/music", dest: "/mnt/media/music/nas1" }
- { src: "nas2.radoncanyon.com:/mnt/etank/media/music", dest: "/mnt/media/music/nas2" }
- { src: "nas1.radoncanyon.com:/mnt/scratch/downloads", dest: "/mnt/downloads/nas1" }
- { src: "nas2.radoncanyon.com:/mnt/scratch/downloads", dest: "/mnt/downloads/nas2" }
zfs_mounts:
- { name: rpool/dockerfs, mountpoint: /dockerfs }
nfs_utils: nfs-utils
docker_sysctls:
  net.ipv4.ip_forward: 1
  net.bridge.bridge-nf-call-ip6tables: 1
  net.bridge.bridge-nf-call-iptables: 1
  net.netfilter.nf_conntrack_max: 1000000
  net.core.somaxconn: 1024
  vm.panic_on_oom: 1
  kernel.panic: 10
