---
docker_daemon_port: 2376
nfs_mounts:
  - { src: "freenas.radoncanyon.com:/mnt/etank/media/tv", dest: "/mnt/media/tv" }
  - { src: "freenas.radoncanyon.com:/mnt/etank/media/movies", dest: "/mnt/media/movies" }
  - { src: "freenas.radoncanyon.com:/mnt/etank/media/anime", dest: "/mnt/media/anime" }
  - { src: "freenas.radoncanyon.com:/mnt/etank/media/downloads", dest: "/mnt/downloads" }
dockerfs_dirs:
  - { name: "pms/transcode" }
zfs_mounts:
  - { name: rpool/dockerfs, mountpoint: /dockerfs }
nfs_utils: nfs-utils
