---
- name: Install common packages
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: present

- name: Add Nick's group
  ansible.builtin.group:
    name: nlopez
    state: present
    gid: 1000

- name: Add Nick's superuser
  ansible.builtin.user:
    name: nlopez
    shell: /usr/bin/zsh
    group: nlopez
    groups: "{{ sudo_group }}"
    createhome: true
    uid: 1000

- name: Add Nick to docker group
  ansible.builtin.user:
    name: nlopez
    groups: docker
    append: true
  when: "'docker' in  lookup('pipe', 'cut -d: -f1 /etc/group')"

- name: Setup Nick's keys
  ansible.builtin.authorized_key:
    user: nlopez
    key: https://github.com/nlopez.keys
    exclusive: true
    validate_certs: true

- name: Setup Nick's dotfiles
  ansible.builtin.git:
    repo: https://github.com/nlopez/dotfiles
    bare: true
    dest: /home/nlopez/dotfiles
    version: unstable
  become: true
  become_user: nlopez

- name: Checkout dotfiles
  ansible.builtin.command:
    cmd: /usr/bin/git --git-dir=/home/nlopez/dotfiles --work-tree=/home/nlopez checkout
  become: true
  become_user: nlopez

- name: Allow members of sudoers group to run all commands without a password
  ansible.builtin.template:
    src: sudoers.j2
    dest: "{{ sudoers }}"
    validate: "visudo -cf %s"
    mode: '0600'

- name: Tune networking
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: true
    reload: true
    sysctl_file: /etc/sysctl.d/60-net.conf
    ignoreerrors: true # ignores unknown key errors
  loop: "{{ lookup('dict', net_sysctls) }}"
