---
- name: Ensure the router solicitation daemon is running and enabled
  service: name=rtsold state=started enabled=yes
  when: ansible_os_family == "FreeBSD"

- name: Set locale to en_us.UTF-8
  copy: src=login.conf dest=/etc/login.conf owner=root group=wheel mode=0644
  notify: rebuild capabilities database for login.conf
  when: ansible_os_family == "FreeBSD"

- name: Set locale to en_us.UTF-8
  copy: src=locale.gen dest=/etc/locale.gen owner=root group=root mode=0644
  notify: generate locales
  when: ansible_os_family == "Archlinux"

- name: Install common packages
  package: name=bash,sudo,rsync,{{ system_certificates }},curl,wget,mosh,screen,{{ dig }},tree,{{ vim }} state=present

- name: Set root's shell to bash
  user: name=root shell={{ bash_binary }}

- name: Add Nick's group
  group: name=nlopez state=present

- name: Add Nick's superuser
  user:
    name: nlopez
    shell: "{{ bash_binary }}"
    group: nlopez
    groups: "{{ sudo_group }}"
    createhome: True

- name: Add Nick to docker group
  user: name=nlopez groups=docker append=yes
  ignore_errors: True

- name: Setup Nick's keys
  authorized_key: user=nlopez key=https://github.com/nlopez.keys

- name: Allow members of sudoers group to run all commands without a password
  template: src=sudoers.j2 dest={{ sudoers }} validate='visudo -cf %s'

