---
- name: Install common packages
  package:
    name:   "{{ common_packages }}"
    state: present

- name: Add Nick's group
  group:
    name: nlopez
    state: present
    gid: 1000

- name: Add Nick's superuser
  user:
    name: nlopez
    shell: "{{ lookup('pipe', 'which bash') }}"
    group: nlopez
    groups: "{{ sudo_group }}"
    createhome: True
    uid: 1000

- name: Add Nick to docker group
  user:
    name: nlopez
    groups: docker
    append: yes
  when: "'docker' in  lookup('pipe', 'cut -d: -f1 /etc/group')"

- name: Setup Nick's keys
  authorized_key:
    user: nlopez
    key: https://github.com/nlopez.keys
    exclusive: yes
    validate_certs: yes

- name: Allow members of sudoers group to run all commands without a password
  template:
    src: sudoers.j2
    dest: "{{ sudoers }}"
    validate: 'visudo -cf %s'

- name: Tune networking
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: yes
    reload: yes
    sysctl_file: /etc/sysctl.d/60-net.conf
  loop: "{{ lookup('dict', net_sysctls) }}"
