---
- name: Set hostname
  shell: "hostnamectl set-hostname {{ hostname }}"

- name: Populate hosts file
  template: src=hosts.j2 dest=/etc/hosts mode=0644 owner=root group=root

- name: Configure eth0
  template: src=eth0.j2 dest=/etc/netctl/eth0 mode=0644 owner=root group=root

- name: Install ifplugd
  package: name=ifplugd state=present

- name: Enable and start ifplugd for eth0
  service: name=netctl-ifplugd@eth0.service enabled=yes state=started

- name: Install dnsmasq
  package: name=dnsmasq state=present

- name: Enable and start dnsmasq
  service: name=dnsmasq state=started enabled=yes
