- name: Remove systemd-timesyncd
  ansible.builtin.package:
    name: systemd-timesyncd
    state: absent

- name: Install chrony
  ansible.builtin.package:
    name: chrony
    state: latest

- name: Enable chrony
  ansible.builtin.service:
    name: chrony
    state: started
    enabled: true
