- name: set hostname
  file:
    path: /etc/hostname
    content: "{{ inventory_hostname_short }}"
    mode: 0644
    owner: root
    group: root

- name: populate /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: 0644
    owner: root
    group: root
