- name: set hostname
  hostname:
    name: "{{ inventory_hostname_short }}"

- name: populate /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    mode: 0644
    owner: root
    group: root
