common_packages:
  - bash
  - sudo
  - rsync
  - "{{ system_certificates }}"
  - curl
  - wget
  - mosh
  - screen
  - "{{ dig }}"
  - tree
  - "{{ vim }}"
  - pv
  - tcpdump
  - rng-tools
  - ethtool
  - iperf
  - iperf3
