common_packages:
  - "{{ dig }}"
  - "{{ system_certificates }}"
  - "{{ vim }}"
  - apt-transport-https
  - arping
  - bash
  - bwm-ng
  - curl
  - ethtool
  - git
  - htop
  - iperf
  - iperf3
  - jdupes
  - lsof
  - mosh
  - mosh
  - mtr-tiny
  - ncdu
  - pv
  - rng-tools
  - rsync
  - screen
  - sudo
  - tcpdump
  - tree
  - wget
  - zsh

net_sysctls:
  vm.swappiness: 10
  net.ipv4.ip_local_port_range: 10000 65000
  # http://www.nateware.com/linux-network-tuning-for-2013.html
  # Increase Linux autotuning TCP buffer limits
  # Set max to 16MB for 1GE and 32M (33554432) or 54M (56623104) for 10GE
  # Don't set tcp_mem itself! Let the kernel scale it based on RAM.
  net.core.rmem_max: 16777216
  net.core.wmem_max: 16777216
  net.core.rmem_default: 16777216
  net.core.wmem_default: 16777216
  net.core.optmem_max: 40960
  # cloudflare uses this for balancing latency and throughput
  # https://blog.cloudflare.com/the-story-of-one-latency-spike/
  # https://blog.cloudflare.com/optimizing-tcp-for-high-throughput-and-low-latency/
  net.ipv4.tcp_rmem: 8192 262144 536870912
  net.ipv4.tcp_wmem: 4096 16384 536870912
  # Also increase the max packet backlog
  net.core.netdev_max_backlog: 100000
  net.core.netdev_budget: 50000
  # Make room for more TIME_WAIT sockets due to more clients,
  # and allow them to be reused if we run out of sockets
  net.ipv4.tcp_max_syn_backlog: 30000
  net.ipv4.tcp_max_tw_buckets: 2000000
  net.ipv4.tcp_tw_reuse: 1
  net.ipv4.tcp_fin_timeout: 10
  # Disable TCP slow start on idle connections
  net.ipv4.tcp_slow_start_after_idle: 0
  # If your servers talk UDP, also up these limits
  net.ipv4.udp_rmem_min: 8192
  net.ipv4.udp_wmem_min: 8192
  # Disable source routing and redirects
  net.ipv4.conf.all.send_redirects: 0
  net.ipv4.conf.all.accept_redirects: 0
  net.ipv4.conf.all.accept_source_route: 0
  # Log packets with impossible addresses for security
  net.ipv4.conf.all.log_martians: 1
  # Actual fix for high softirq in 4.13
  net.core.netdev_budget_usecs: 5000
  # https://blog.cloudflare.com/http-2-prioritization-with-nginx/
  net.core.default_qdisc: fq
  net.ipv4.tcp_congestion_control: bbr
  net.ipv4.tcp_notsent_lowat: 16384
  net.ipv4.tcp_adv_win_scale: -2
  net.ipv4.tcp_collapse_max_bytes: 6291456
  # TCP SACK PANIC
  # https://access.redhat.com/security/vulnerabilities/tcpsack
  net.ipv4.tcp_sack: 0
  # https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=19f92a030ca6d772ab44b22ee6a01378a8cb32d4
  net.core.somaxconn: 4096
