---
- name: Configure sshd
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config validate='sshd -T -f %s'
  notify: reload sshd

- name: Ensure the SSH daemon is started and enabled
  service: name=sshd state=started enabled=yes
