---
- name: Configure sshd
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config
  notify: reload sshd

- name: Setup Nick's key(s) for root
  authorized_key: user=root key="{{ item }}" state=present exclusive=yes

  with_file:
    - public_keys/nlopez

- name: Start the sshd process
  service: name=sshd state=started enabled=yes
